import type { Linter } from 'eslint';

export const defaultRules: Partial<Linter.RulesRecord> = {
    'accessor-pairs': ['off'],
    'array-bracket-newline': ['off', 'consistent'],
    'array-bracket-spacing': ['off', 'never'],
    'array-callback-return': [
        'error',
        {
            allowImplicit: true,
            allowVoid: false,
            checkForEach: false,
        },
    ],
    'array-element-newline': [
        'off',
        {
            minItems: 3,
            multiline: true,
        },
    ],
    'arrow-body-style': ['warn', 'as-needed'],
    'arrow-parens': ['off', 'always'],
    'arrow-spacing': [
        'off',
        {
            after: true,
            before: true,
        },
    ],
    'block-scoped-var': ['error'],
    'block-spacing': ['off', 'always'],
    'brace-style': [
        'off',
        '1tbs',
        {
            allowSingleLine: true,
        },
    ],
    'callback-return': ['off'],
    camelcase: [
        'error',
        {
            ignoreDestructuring: false,
            ignoreGlobals: false,
            ignoreImports: false,
            properties: 'never',
        },
    ],
    'capitalized-comments': [
        'off',
        'never',
        {
            block: {
                ignoreConsecutiveComments: true,
                ignoreInlineComments: true,
                ignorePattern: '.*',
            },
            line: {
                ignoreConsecutiveComments: true,
                ignoreInlineComments: true,
                ignorePattern: '.*',
            },
        },
    ],
    'class-methods-use-this': [
        'warn',
        {
            enforceForClassFields: true,
            exceptMethods: [
                'render',
                'getInitialState',
                'getDefaultProps',
                'getChildContext',
                'componentWillMount',
                'UNSAFE_componentWillMount',
                'componentDidMount',
                'componentWillReceiveProps',
                'UNSAFE_componentWillReceiveProps',
                'shouldComponentUpdate',
                'componentWillUpdate',
                'UNSAFE_componentWillUpdate',
                'componentDidUpdate',
                'componentWillUnmount',
                'componentDidCatch',
                'getSnapshotBeforeUpdate',
            ],
        },
    ],
    'comma-dangle': [
        'off',
        {
            arrays: 'always-multiline',
            exports: 'always-multiline',
            functions: 'always-multiline',
            imports: 'always-multiline',
            objects: 'always-multiline',
        },
    ],
    'comma-spacing': [
        'off',
        {
            after: true,
            before: false,
        },
    ],
    'comma-style': [
        'off',
        'last',
        {
            exceptions: {
                ArrayExpression: false,
                ArrayPattern: false,
                ArrowFunctionExpression: false,
                CallExpression: false,
                FunctionDeclaration: false,
                FunctionExpression: false,
                ImportDeclaration: false,
                NewExpression: false,
                ObjectExpression: false,
                ObjectPattern: false,
                VariableDeclaration: false,
            },
        },
    ],
    complexity: ['off', 20],
    'computed-property-spacing': ['off', 'never'],
    'consistent-return': ['off'],
    'consistent-this': ['off'],
    'constructor-super': ['error'],
    curly: ['off', 'multi-line'],
    'default-case': [
        'off',
        {
            commentPattern: '^no default$',
        },
    ],
    'default-case-last': ['error'],
    'default-param-last': ['error'],
    'dot-location': ['off', 'property'],
    'dot-notation': [
        'error',
        {
            allowKeywords: true,
            allowPattern: '',
        },
    ],

    'eol-last': ['off', 'always'],
    eqeqeq: [
        'error',
        'always',
        {
            null: 'ignore',
        },
    ],
    'for-direction': ['error'],
    'func-call-spacing': ['off', 'never'],
    'func-name-matching': [
        'off',
        'always',
        {
            considerPropertyDescriptor: true,
            includeCommonJSModuleExports: false,
        },
    ],
    'func-names': ['warn'],
    'func-style': ['off', 'expression'],
    'function-call-argument-newline': ['off', 'consistent'],
    'function-paren-newline': ['off', 'multiline-arguments'],
    'generator-star': ['off'],
    'generator-star-spacing': [
        'off',
        {
            after: true,
            before: false,
        },
    ],
    'getter-return': [
        'warn',
        {
            allowImplicit: true,
        },
    ],
    'global-require': ['off'],
    'grouped-accessor-pairs': ['error'],
    'guard-for-in': ['error'],
    'handle-callback-err': ['off'],
    'id-denylist': ['off'],
    'id-length': ['off'],
    'id-match': ['off'],
    'implicit-arrow-linebreak': ['off', 'beside'],
    indent: [
        'off',
        2,
        {
            ArrayExpression: 1,
            CallExpression: {
                arguments: 1,
            },
            FunctionDeclaration: {
                body: 1,
                parameters: 1,
            },
            FunctionExpression: {
                body: 1,
                parameters: 1,
            },
            ImportDeclaration: 1,
            ObjectExpression: 1,
            SwitchCase: 1,
            VariableDeclarator: 1,
            flatTernaryExpressions: false,
            ignoreComments: false,
            ignoredNodes: [
                'JSXElement',
                'JSXElement > *',
                'JSXAttribute',
                'JSXIdentifier',
                'JSXNamespacedName',
                'JSXMemberExpression',
                'JSXSpreadAttribute',
                'JSXExpressionContainer',
                'JSXOpeningElement',
                'JSXClosingElement',
                'JSXFragment',
                'JSXOpeningFragment',
                'JSXClosingFragment',
                'JSXText',
                'JSXEmptyExpression',
                'JSXSpreadChild',
            ],
            offsetTernaryExpressions: false,
            outerIIFEBody: 1,
        },
    ],
    'indent-legacy': ['off'],
    'init-declarations': ['off'],
    'jsx-quotes': ['off', 'prefer-double'],
    'key-spacing': [
        'off',
        {
            afterColon: true,
            beforeColon: false,
        },
    ],
    'keyword-spacing': [
        'off',
        {
            after: true,
            before: true,
            overrides: {
                case: {
                    after: true,
                },
                return: {
                    after: true,
                },
                throw: {
                    after: true,
                },
            },
        },
    ],
    'line-comment-position': [
        'off',
        {
            applyDefaultPatterns: true,
            ignorePattern: '',
            position: 'above',
        },
    ],
    'linebreak-style': ['off', 'unix'],
    'lines-around-comment': ['off'],
    'lines-around-directive': [
        'error',
        {
            after: 'always',
            before: 'always',
        },
    ],
    'lines-between-class-members': [
        'error',
        'always',
        {
            exceptAfterSingleLine: false,
        },
    ],
    'max-classes-per-file': ['error', 1],
    'max-depth': ['off', 4],
    'max-len': [
        'off',
        100,
        2,
        {
            ignoreComments: false,
            ignoreRegExpLiterals: true,
            ignoreStrings: true,
            ignoreTemplateLiterals: true,
            ignoreUrls: true,
        },
    ],
    'max-lines': [
        'off',
        {
            max: 300,
            skipBlankLines: true,
            skipComments: true,
        },
    ],
    'max-lines-per-function': [
        'off',
        {
            IIFEs: true,
            max: 50,
            skipBlankLines: true,
            skipComments: true,
        },
    ],
    'max-nested-callbacks': ['off'],
    'max-params': ['off', 3],
    'max-statements': ['off', 10],
    'max-statements-per-line': [
        'off',
        {
            max: 1,
        },
    ],
    'media-has-caption': ['off'],
    'multiline-comment-style': ['off', 'starred-block'],
    'multiline-ternary': ['off', 'never'],
    'new-cap': [
        'error',
        {
            capIsNew: false,
            capIsNewExceptions: ['Immutable.Map', 'Immutable.Set', 'Immutable.List'],
            newIsCap: true,
            newIsCapExceptions: [],
            properties: true,
        },
    ],
    'new-parens': ['off'],
    'newline-after-var': ['off'],
    'newline-before-return': ['off'],
    'newline-per-chained-call': [
        'off',
        {
            ignoreChainWithDepth: 4,
        },
    ],
    'no-alert': ['warn'],
    'no-array-constructor': ['off'],
    'no-arrow-condition': ['off'],
    'no-async-promise-executor': ['error'],
    'no-await-in-loop': ['off'],
    'no-bitwise': ['error'],
    'no-buffer-constructor': ['error'],
    'no-caller': ['error'],
    'no-case-declarations': ['error'],
    'no-catch-shadow': ['off'],
    'no-class-assign': ['error'],
    'no-comma-dangle': ['off'],
    'no-compare-neg-zero': ['error'],
    'no-cond-assign': ['error', 'always'],
    'no-confusing-arrow': [
        'off',
        {
            allowParens: true,
            onlyOneSimpleParam: false,
        },
    ],
    'no-console': ['off'],
    'no-const-assign': ['error'],
    'no-constant-condition': ['warn'],
    'no-constructor-return': ['error'],
    'no-continue': ['error'],
    'no-control-regex': ['error'],
    'no-debugger': ['error'],
    'no-delete-var': ['error'],
    'no-div-regex': ['off'],
    'no-dupe-args': ['error'],
    'no-dupe-class-members': ['error'],
    'no-dupe-else-if': ['error'],
    'no-dupe-keys': ['error'],
    'no-duplicate-case': ['error'],
    'no-duplicate-imports': ['off'],
    'no-else-return': [
        'error',
        {
            allowElseIf: false,
        },
    ],
    'no-empty': ['error'],
    'no-empty-character-class': ['error'],
    'no-empty-function': [
        'error',
        {
            allow: ['arrowFunctions', 'functions', 'methods'],
        },
    ],
    'no-empty-pattern': ['error'],
    'no-eq-null': ['off'],
    'no-eval': ['error'],
    'no-ex-assign': ['error'],
    'no-extend-native': ['error'],
    'no-extra-bind': ['error'],
    'no-extra-boolean-cast': ['error'],
    'no-extra-label': ['error'],
    'no-extra-parens': [
        'off',
        'all',
        {
            conditionalAssign: true,
            enforceForArrowConditionals: false,
            ignoreJSX: 'all',
            nestedBinaryExpressions: false,
            returnAssign: false,
        },
    ],
    'no-extra-semi': ['off'],
    'no-fallthrough': ['error'],
    'no-floating-decimal': ['off'],
    'no-func-assign': ['error'],
    'no-global-assign': [
        'error',
        {
            exceptions: [],
        },
    ],
    'no-implicit-coercion': [
        'off',
        {
            allow: [],
            boolean: false,
            number: true,
            string: true,
        },
    ],
    'no-implicit-globals': ['off'],
    'no-implied-eval': ['error'],
    'no-import-assign': ['error'],
    'no-inline-comments': ['off'],
    'no-inner-declarations': ['error'],
    'no-invalid-regexp': ['error'],
    'no-invalid-this': ['off'],
    'no-irregular-whitespace': ['error'],
    'no-iterator': ['error'],
    'no-label-var': ['error'],
    'no-labels': [
        'error',
        {
            allowLoop: false,
            allowSwitch: false,
        },
    ],
    'no-lone-blocks': ['error'],
    'no-lonely-if': ['error'],
    'no-loop-func': ['error'],
    'no-loss-of-precision': ['off'],
    'no-magic-numbers': [
        'off',
        {
            detectObjects: false,
            enforceConst: true,
            ignore: [],
            ignoreArrayIndexes: true,
        },
    ],
    'no-misleading-character-class': ['error'],
    'no-mixed-operators': [
        'off',
        {
            allowSamePrecedence: false,
            groups: [
                ['%', '**'],
                ['%', '+'],
                ['%', '-'],
                ['%', '*'],
                ['%', '/'],
                ['/', '*'],
                ['&', '|', '<<', '>>', '>>>'],
                ['==', '!=', '===', '!=='],
                ['&&', '||'],
            ],
        },
    ],
    'no-mixed-requires': ['off', false],
    'no-mixed-spaces-and-tabs': ['off'],
    'no-multi-assign': ['error'],
    'no-multi-spaces': [
        'off',
        {
            ignoreEOLComments: false,
        },
    ],
    'no-multi-str': ['error'],
    'no-multiple-empty-lines': [
        'off',
        {
            max: 1,
            maxBOF: 0,
            maxEOF: 0,
        },
    ],
    'no-native-reassign': ['off'],
    'no-negated-condition': ['off'],
    'no-negated-in-lhs': ['off'],
    'no-nested-ternary': ['error'],
    'no-new': ['error'],
    'no-new-func': ['error'],
    'no-new-object': ['error'],
    'no-new-require': ['error'],
    'no-new-symbol': ['error'],
    'no-new-wrappers': ['error'],
    'no-nonoctal-decimal-escape': ['error'],
    'no-obj-calls': ['error'],
    'no-octal': ['error'],
    'no-octal-escape': ['error'],
    'no-param-reassign': [
        'off',
        {
            ignorePropertyModificationsFor: [
                'acc',
                'accumulator',
                'e',
                'ctx',
                'context',
                'req',
                'request',
                'res',
                'response',
                '$scope',
                'staticContext',
            ],
            props: true,
        },
    ],
    'no-path-concat': ['error'],
    'no-plusplus': ['off'],
    'no-process-env': ['off'],
    'no-process-exit': ['off'],
    'no-promise-executor-return': ['error'],
    'no-proto': ['error'],
    'no-prototype-builtins': ['error'],
    'no-redeclare': ['error'],
    'no-regex-spaces': ['error'],
    'no-reserved-keys': ['off'],
    'no-restricted-exports': [
        'error',
        {
            restrictedNamedExports: ['default', 'then'],
        },
    ],
    'no-restricted-globals': [
        'off',
        {
            message: 'Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite',
            name: 'isFinite',
        },
        {
            message: 'Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan',
            name: 'isNaN',
        },
        'addEventListener',
        'blur',
        'close',
        'closed',
        'confirm',
        'defaultStatus',
        'defaultstatus',
        'event',
        'external',
        'find',
        'focus',
        'frameElement',
        'frames',
        'history',
        'innerHeight',
        'innerWidth',
        'length',
        'location',
        'locationbar',
        'menubar',
        'moveBy',
        'moveTo',
        'name',
        'onblur',
        'onerror',
        'onfocus',
        'onload',
        'onresize',
        'onunload',
        'open',
        'opener',
        'opera',
        'outerHeight',
        'outerWidth',
        'pageXOffset',
        'pageYOffset',
        'parent',
        'print',
        'removeEventListener',
        'resizeBy',
        'resizeTo',
        'screen',
        'screenLeft',
        'screenTop',
        'screenX',
        'screenY',
        'scroll',
        'scrollbars',
        'scrollBy',
        'scrollTo',
        'scrollX',
        'scrollY',
        'self',
        'status',
        'statusbar',
        'stop',
        'toolbar',
        'top',
    ],
    'no-restricted-imports': [
        'off',
        {
            paths: [],
            patterns: [],
        },
    ],
    'no-restricted-modules': ['off'],
    'no-restricted-properties': [
        'warn',
        {
            message: 'Please use square brackets to access array element with index.',
            property: 'at',
        },
    ],
    'no-restricted-syntax': [
        'off',
        {
            message:
                'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.',
            selector: 'ForInStatement',
        },
        {
            message:
                'iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations.',
            selector: 'ForOfStatement',
        },
        {
            message: 'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
            selector: 'LabeledStatement',
        },
        {
            message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.',
            selector: 'WithStatement',
        },
    ],
    'no-return-assign': ['error', 'always'],
    'no-return-await': ['error'],
    'no-script-url': ['error'],
    'no-self-assign': [
        'error',
        {
            props: true,
        },
    ],
    'no-self-compare': ['error'],
    'no-sequences': ['error'],
    'no-setter-return': ['error'],
    'no-shadow': ['off'],
    'no-shadow-restricted-names': ['error'],
    'no-space-before-semi': ['off'],
    'no-spaced-func': ['off'],
    'no-sparse-arrays': ['error'],
    'no-sync': ['off'],
    'no-tabs': ['off'],
    'no-template-curly-in-string': ['error'],
    'no-ternary': ['off'],
    'no-this-before-super': ['error'],
    'no-throw-literal': ['error'],
    'no-trailing-spaces': [
        'off',
        {
            ignoreComments: false,
            skipBlankLines: false,
        },
    ],
    'no-undef': ['off'],
    'no-undef-init': ['error'],
    'no-undefined': ['off'],
    'no-underscore-dangle': [
        'warn',
        {
            allow: ['__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'],
            allowAfterSuper: false,
            allowAfterThis: false,
            allowAfterThisConstructor: false,
            allowFunctionParams: true,
            allowInArrayDestructuring: true,
            allowInObjectDestructuring: true,
            enforceInClassFields: false,
            enforceInMethodNames: true,
        },
    ],
    'no-unexpected-multiline': ['off'],
    'no-unmodified-loop-condition': ['off'],
    'no-unneeded-ternary': [
        'error',
        {
            defaultAssignment: false,
        },
    ],
    'no-unreachable': ['error'],
    'no-unreachable-loop': [
        'error',
        {
            ignore: [],
        },
    ],
    'no-unsafe-finally': ['error'],
    'no-unsafe-negation': ['error'],
    'no-unsafe-optional-chaining': [
        'error',
        {
            disallowArithmeticOperators: true,
        },
    ],
    'no-unused-expressions': [
        'error',
        {
            allowShortCircuit: false,
            allowTaggedTemplates: false,
            allowTernary: false,
            enforceForJSX: false,
        },
    ],
    'no-unused-labels': ['error'],
    'no-unused-private-class-members': ['off'],
    'no-unused-vars': 'off',
    'no-use-before-define': [
        'off',
        {
            classes: true,
            functions: true,
            variables: true,
        },
    ],
    'no-useless-backreference': ['error'],
    'no-useless-call': ['off'],
    'no-useless-catch': ['error'],
    'no-useless-computed-key': ['error'],
    'no-useless-concat': ['error'],
    'no-useless-constructor': ['error'],
    'no-useless-escape': ['error'],
    'no-useless-rename': [
        'error',
        {
            ignoreDestructuring: false,
            ignoreExport: false,
            ignoreImport: false,
        },
    ],
    'no-useless-return': ['error'],
    'no-var': ['error'],
    'no-void': ['error'],
    'no-warning-comments': [
        'off',
        {
            location: 'start',
            terms: ['todo', 'fixme', 'xxx'],
        },
    ],
    'no-whitespace-before-property': ['off'],
    'no-with': ['error'],
    'no-wrap-func': ['off'],
    'node/file-extension-in-import': [
        'warn',
        'always',
        {
            '.js': 'never',
            '.jsx': 'never',
            '.ts': 'never',
            '.tsx': 'never',
        },
    ],
    'nonblock-statement-body-position': [
        'off',
        'beside',
        {
            overrides: {},
        },
    ],
    'object-curly-newline': [
        'off',
        {
            ExportDeclaration: {
                consistent: true,
                minProperties: 4,
                multiline: true,
            },
            ImportDeclaration: {
                consistent: true,
                minProperties: 4,
                multiline: true,
            },
            ObjectExpression: {
                consistent: true,
                minProperties: 4,
                multiline: true,
            },
            ObjectPattern: {
                consistent: true,
                minProperties: 4,
                multiline: true,
            },
        },
    ],
    'object-curly-spacing': ['off', 'always'],
    'object-property-newline': [
        'off',
        {
            allowAllPropertiesOnSameLine: true,
            allowMultiplePropertiesPerLine: false,
        },
    ],
    'object-shorthand': [
        'error',
        'always',
        {
            avoidQuotes: true,
            ignoreConstructors: false,
        },
    ],
    'one-var': ['error', 'never'],
    'one-var-declaration-per-line': ['off', 'always'],
    'operator-assignment': ['error', 'always'],
    'operator-linebreak': [
        'off',
        'before',
        {
            overrides: {
                '=': 'none',
            },
        },
    ],
    'padded-blocks': [
        'off',
        {
            blocks: 'never',
            classes: 'never',
            switches: 'never',
        },
        {
            allowSingleLineBlocks: true,
        },
    ],
    'padding-line-between-statements': [
        'warn',
        {
            blankLine: 'always',
            next: 'return',
            prev: '*',
        },
    ],
    'prefer-arrow-callback': [
        'off',
        {
            allowNamedFunctions: false,
            allowUnboundThis: true,
        },
    ],
    'prefer-const': [
        'error',
        {
            destructuring: 'any',
            ignoreReadBeforeAssign: true,
        },
    ],
    'prefer-destructuring': [
        'error',
        {
            AssignmentExpression: {
                array: true,
                object: false,
            },
            VariableDeclarator: {
                array: false,
                object: true,
            },
        },
        {
            enforceForRenamedProperties: false,
        },
    ],
    'prefer-exponentiation-operator': ['error'],
    'prefer-named-capture-group': ['off'],
    'prefer-numeric-literals': ['error'],
    'prefer-object-spread': ['error'],
    'prefer-promise-reject-errors': [
        'off',
        {
            allowEmptyReject: true,
        },
    ],
    'prefer-reflect': ['off'],
    'prefer-regex-literals': [
        'error',
        {
            disallowRedundantWrapping: true,
        },
    ],
    'prefer-rest-params': ['error'],
    'prefer-spread': ['error'],
    'prefer-template': ['error'],
    'prettier/prettier': ['error'],
    'quote-props': [
        'off',
        'as-needed',
        {
            keywords: false,
            numbers: false,
            unnecessary: true,
        },
    ],
    quotes: [
        'off',
        'single',
        {
            avoidEscape: true,
        },
    ],
    radix: ['error'],

    'require-atomic-updates': ['off'],
    'require-await': ['off'],
    'require-jsdoc': ['off'],
    'require-unicode-regexp': ['off'],
    'require-yield': ['error'],
    'rest-spread-spacing': ['off', 'never'],
    semi: ['off', 'always'],
    'semi-spacing': [
        'off',
        {
            after: true,
            before: false,
        },
    ],
    'semi-style': ['off', 'last'],

    'sort-imports': [
        'off',
        {
            ignoreCase: false,
            ignoreDeclarationSort: false,
            ignoreMemberSort: false,
            memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
        },
    ],
    'sort-keys': [
        'off',
        'asc',
        {
            caseSensitive: false,
            natural: true,
        },
    ],
    'sort-vars': ['off'],
    'space-after-function-name': ['off'],
    'space-after-keywords': ['off'],
    'space-before-blocks': ['off'],
    'space-before-function-paren': [
        'off',
        {
            anonymous: 'always',
            asyncArrow: 'always',
            named: 'never',
        },
    ],
    'space-before-function-parentheses': ['off'],
    'space-before-keywords': ['off'],
    'space-in-brackets': ['off'],
    'space-in-parens': ['off', 'never'],
    'space-infix-ops': ['off'],
    'space-return-throw-case': ['off'],
    'space-unary-ops': [
        'off',
        {
            nonwords: false,
            overrides: {},
            words: true,
        },
    ],
    'space-unary-word-ops': ['off'],
    'spaced-comment': [
        'error',
        'always',
        {
            block: {
                balanced: true,
                exceptions: ['-', '+'],
                markers: ['=', '!', ':', '::'],
            },
            line: {
                exceptions: ['-', '+'],
                markers: ['=', '!', '/'],
            },
        },
    ],
    strict: ['error', 'never'],
    'switch-colon-spacing': [
        'off',
        {
            after: true,
            before: false,
        },
    ],
    'symbol-description': ['error'],
    'template-curly-spacing': ['off'],
    'template-tag-spacing': ['off', 'never'],
    'unicode-bom': ['off', 'never'],
    'use-isnan': ['error'],
    'valid-jsdoc': ['off'],
    'valid-typeof': [
        'error',
        {
            requireStringLiterals: true,
        },
    ],
    'vars-on-top': ['error'],
    'wrap-iife': [
        'off',
        'outside',
        {
            functionPrototypeMethods: false,
        },
    ],
    'wrap-regex': ['off'],
    'yield-star-spacing': ['off', 'after'],
    yoda: ['error'],
};
