name: "Run Linters and Tests"
description: "Installs Node.js and uses Yarn to install dependencies"
runs:
  using: "composite"
  steps:
    - name: Run Linters
      if: always()
      shell: bash
      run: yarn lint

    - name: Run Tests
      if: always()
      shell: bash
      run: yarn test

    - name: Upload src/app/__screenshots__ as artifact if tests fail
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: failed-test-artifacts
        path: |
          ./src/app/__screenshots__
          ./__screenshots-current__
          ./coverage
