name: "Run Linters and Tests"
description: "Installs Node.js and uses Yarn to install dependencies"
runs:
  using: "composite"
  steps:
    - name: Run Linters
      if: always()
      shell: bash
      run: yarn lint

    - name: Build Tests Server
      if: always()
      shell: bash
      run: yarn test:build

    - name: Run e2e Tests
      if: always()
      shell: bash
      run: yarn test:e2e

    - name: Run unit Tests
      if: always()
      shell: bash
      run: yarn test:unit

    - name: Run screenshot Server
      if: always()
      shell: bash
      run: yarn test:screenshot

    - name: Upload src/app/__screenshots__ as artifact if tests fail
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: failed-test-artifacts
        path: |
          ./__screenshots-current__
          ./__screenshots-dif__
          ./__screenshots-reference__
          ./coverage
