name: E2E Production

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.2-jammy

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Replace Characters in Repository Name
      run: |
        ORIGINAL_VALUE="${{ github.repository }}/"
        MODIFIED_VALUE="${ORIGINAL_VALUE/${{ github.repository_owner }}/}"
        echo "PRODUCTION_SERVER_URL="https://${{ github.repository_owner }}.github.io$MODIFIED_VALUE"" >> $GITHUB_ENV
      shell: bash

    - name: Install Node.js and Dependencies
      uses: ./.github/actions/install-node  # Путь до вашего локального action
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run Tests Chromium
      if: always()
      env:
        E2E_BROWSER_NAME: chromium
      run: yarn test:e2e:production

    - name: Run Tests Firefox
      if: always()
      env:
        E2E_BROWSER_NAME: firefox
        HOME: /root
      run: yarn test:e2e:production

    - name: Run Tests Webkit
      if: always()
      env:
        E2E_BROWSER_NAME: webkit
      run: yarn test:e2e:production

    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: e2e-test-run
        path: ./__screenshots-current__
