name: Main Pull Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.2-jammy

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Add env
      uses: ./.github/actions/add-env

    - name: Install Node.js and Dependencies
      uses: ./.github/actions/install-node
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run Lint and Test
      uses: ./.github/actions/lint-and-test